# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kQ9Hw9vwt26Hr3fgDYCaYeAXA3CKsZ07
"""

class MyHashMap:
    def __init__(self):
        self.data=[]

    def put(self, key: int, value: int) -> None:
        for item in self.data:
          if item[0] == key:
            item[1]= value
            return
        self.data.append([key, value])
        return

    def get(self, key: int) -> int:
        for item in self.data:
          if item[0] == key:
            return item[1]
        return -1

    def remove(self, key: int) -> None:
        for item in self.data:
          if item[0] == key:
            self.data.remove(item)
            return
    def print(self):
      print(self.data)

#initial test case

obj = MyHashMap()
obj.print()
obj.put(1,1)
obj.print()
obj.put(2,2)
obj.print()
print(obj.get(1))
print(obj.get(3))
obj.put(2,1)
obj.print()
print(obj.get(2))
obj.remove(2)
obj.print()
obj.get(2)

["MyHashMap", "put", "put", "get", "get", "put", "get", "remove", "get"]
[[], [1, 1], [2, 2], [1], [3], [2, 1], [2], [2], [2]]